import type { Registry, StockTokenEntry } from '../types.js';
import { MAINNET_CHAIN_ID } from '../types.js';

const stockTokenEntries: ReadonlyArray<StockTokenEntry> = [
  {
    name: 'Apple Inc.',
    key: 'AAPL',
    chainId: MAINNET_CHAIN_ID,
    address: '0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical AAPL Stock Token',
    ticker: 'AAPL',
    assetType: 'stock',
  },
  {
    name: 'Advanced Micro Devices',
    key: 'AMD',
    chainId: MAINNET_CHAIN_ID,
    address: '0x86923f96303D656E4aa86D9d42D1e57ad2023fdC',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical AMD Stock Token',
    ticker: 'AMD',
    assetType: 'stock',
  },
  {
    name: 'Amazon.com Inc.',
    key: 'AMZN',
    chainId: MAINNET_CHAIN_ID,
    address: '0x12f190a9F9d7D37a250758b26824B97CE941bF54',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical AMZN Stock Token',
    ticker: 'AMZN',
    assetType: 'stock',
  },
  {
    name: 'Alibaba Group',
    key: 'BABA',
    chainId: MAINNET_CHAIN_ID,
    address: '0xad25Ac6C84D497db898fa1E8387bf6Af3532a1c4',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical BABA Stock Token',
    ticker: 'BABA',
    assetType: 'stock',
  },
  {
    name: 'Bloom Energy',
    key: 'BE',
    chainId: MAINNET_CHAIN_ID,
    address: '0x822CC93fFD030293E9842c30BBD678F530701867',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical BE Stock Token',
    ticker: 'BE',
    assetType: 'stock',
  },
  {
    name: 'Coinbase Global',
    key: 'COIN',
    chainId: MAINNET_CHAIN_ID,
    address: '0x6330D8C3178a418788dF01a47479c0ce7CCF450b',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical COIN Stock Token',
    ticker: 'COIN',
    assetType: 'stock',
  },
  {
    name: 'Circle Internet Group',
    key: 'CRCL',
    chainId: MAINNET_CHAIN_ID,
    address: '0xdF0992E440dD0be65BD8439b609d6D4366bf1CB5',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical CRCL Stock Token',
    ticker: 'CRCL',
    assetType: 'stock',
  },
  {
    name: 'CoreWeave',
    key: 'CRWV',
    chainId: MAINNET_CHAIN_ID,
    address: '0x5f10A1C971B69e47e059e1dC91901B59b3fB49C3',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical CRWV Stock Token',
    ticker: 'CRWV',
    assetType: 'stock',
  },
  {
    name: 'Alphabet Inc.',
    key: 'GOOGL',
    chainId: MAINNET_CHAIN_ID,
    address: '0x2e0847E8910a9732eB3fb1bb4b70a580ADAD4FE3',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical GOOGL Stock Token',
    ticker: 'GOOGL',
    assetType: 'stock',
  },
  {
    name: 'Intel Corporation',
    key: 'INTC',
    chainId: MAINNET_CHAIN_ID,
    address: '0xc72b96e0E48ecd4DC75E1e45396e26300BC39681',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical INTC Stock Token',
    ticker: 'INTC',
    assetType: 'stock',
  },
  {
    name: 'Meta Platforms',
    key: 'META',
    chainId: MAINNET_CHAIN_ID,
    address: '0xc0D6457C16Cc70d6790Dd43521C899C87ce02f35',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical META Stock Token',
    ticker: 'META',
    assetType: 'stock',
  },
  {
    name: 'Microsoft Corporation',
    key: 'MSFT',
    chainId: MAINNET_CHAIN_ID,
    address: '0xe93237C50D904957Cf27E7B1133b510C669c2e74',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical MSFT Stock Token',
    ticker: 'MSFT',
    assetType: 'stock',
  },
  {
    name: 'Micron Technology',
    key: 'MU',
    chainId: MAINNET_CHAIN_ID,
    address: '0xfF080c8ce2E5feadaCa0Da81314Ae59D232d4afD',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical MU Stock Token',
    ticker: 'MU',
    assetType: 'stock',
  },
  {
    name: 'NVIDIA Corporation',
    key: 'NVDA',
    chainId: MAINNET_CHAIN_ID,
    address: '0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical NVDA Stock Token',
    ticker: 'NVDA',
    assetType: 'stock',
  },
  {
    name: 'Oracle Corporation',
    key: 'ORCL',
    chainId: MAINNET_CHAIN_ID,
    address: '0xb0992820E760d836549ba69BC7598b4af75dEE03',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical ORCL Stock Token',
    ticker: 'ORCL',
    assetType: 'stock',
  },
  {
    name: 'Palantir Technologies',
    key: 'PLTR',
    chainId: MAINNET_CHAIN_ID,
    address: '0x894E1EC2D74FFE5AEF8Dc8A9e84686acCB964F2A',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical PLTR Stock Token',
    ticker: 'PLTR',
    assetType: 'stock',
  },
  {
    name: 'SanDisk',
    key: 'SNDK',
    chainId: MAINNET_CHAIN_ID,
    address: '0xB90A19fF0Af67f7779afF50A882A9CfF42446400',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical SNDK Stock Token',
    ticker: 'SNDK',
    assetType: 'stock',
  },
  {
    name: 'S&P 500 Index',
    key: 'SPCX',
    chainId: MAINNET_CHAIN_ID,
    address: '0x4a0E65A3EcceC6dBe60AE065F2e7bb85Fae35eEa',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical SPCX Stock Token',
    ticker: 'SPCX',
    assetType: 'stock',
  },
  {
    name: 'Tesla Inc.',
    key: 'TSLA',
    chainId: MAINNET_CHAIN_ID,
    address: '0x322F0929c4625eD5bAd873c95208D54E1c003b2d',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical TSLA Stock Token',
    ticker: 'TSLA',
    assetType: 'stock',
  },
  {
    name: 'USAR',
    key: 'USAR',
    chainId: MAINNET_CHAIN_ID,
    address: '0xd917B029C761D264c6A312BBbcDA868658eF86a6',
    role: 'stock-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical USAR Stock Token',
    ticker: 'USAR',
    assetType: 'stock',
  },
  {
    name: 'Invesco QQQ Trust',
    key: 'QQQ',
    chainId: MAINNET_CHAIN_ID,
    address: '0xD5f3879160bc7c32ebb4dC785F8a4F505888de68',
    role: 'etf-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical QQQ ETF Token',
    ticker: 'QQQ',
    assetType: 'etf',
  },
  {
    name: 'iShares 0-3 Month Treasury Bond',
    key: 'SGOV',
    chainId: MAINNET_CHAIN_ID,
    address: '0x92FD66527192E3e61d4DDd13322Aa222DE86F9B5',
    role: 'etf-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical SGOV ETF Token',
    ticker: 'SGOV',
    assetType: 'etf',
  },
  {
    name: 'iShares Silver Trust',
    key: 'SLV',
    chainId: MAINNET_CHAIN_ID,
    address: '0x411eFb0E7f985935DAec3D4C3ebaEa0d0AD7D89f',
    role: 'etf-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical SLV ETF Token',
    ticker: 'SLV',
    assetType: 'etf',
  },
  {
    name: 'SPDR S&P 500 ETF Trust',
    key: 'SPY',
    chainId: MAINNET_CHAIN_ID,
    address: '0x117cc2133c37B721F49dE2A7a74833232B3B4C0C',
    role: 'etf-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical SPY ETF Token',
    ticker: 'SPY',
    assetType: 'etf',
  },
  {
    name: 'CUSO',
    key: 'CUSO',
    chainId: MAINNET_CHAIN_ID,
    address: '0xa30FA36Db767ad9eD3f7a60fC79526fB4d56D344',
    role: 'etf-token',
    officialSource: 'https://docs.robinhood.com/chain/contracts/',
    verificationDate: '2026-07-13',
    runtimeBytecodeHash: null,
    enabled: true,
    notes: 'Canonical CUSO ETF Token',
    ticker: 'CUSO',
    assetType: 'etf',
  },
] as const;

export const stockTokenRegistry: Registry<StockTokenEntry> = {
  name: 'Canonical Stock Tokens and ETFs',
  version: {
    version: '1.0.0',
    createdAt: '2026-07-13',
  },
  entries: stockTokenEntries,
};
