'use client';

import { useState } from 'react';
import { apiRequest, chainId } from '../../../lib/api';

type AiReport = {
  model: string;
  generatedAt: string;
  report: {
    summary: string;
    highlights: readonly string[];
    watchouts: readonly string[];
    disclaimer: string;
  };
};

/**
 * An on-demand AI read of the token's live facts (price, liquidity, volume,
 * holders, pools). The call is generated behind a button rather than on load:
 * the report costs a model call, and it is cached server-side, so one reader's
 * request serves the rest. It narrates live data only; it does not score.
 */
export function AiReportPanel({ address }: { address: string }) {
  const [result, setResult] = useState<AiReport | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [disabled, setDisabled] = useState(false);

  async function generate() {
    setBusy(true);
    setError(null);
    const response = await apiRequest<AiReport>(
      `/v1/tokens/${encodeURIComponent(address)}/ai-report?chainId=${chainId()}`,
    );
    setBusy(false);
    if (response.ok) {
      setResult(response.data);
      return;
    }
    if (response.code === 'AI_REPORT_DISABLED') {
      setDisabled(true);
      return;
    }
    setError(response.message);
  }

  if (disabled) return null;

  return (
    <section className="panel">
      <h2>AI report</h2>
      <p className="muted">
        A plain-language read of this token’s live market and on-chain facts. Generated by an AI
        model from live data — an overview, not financial advice, and not a risk score.
      </p>
      {result === null ? (
        <button className="primary" type="button" onClick={generate} disabled={busy}>
          {busy ? 'Generating…' : 'Generate AI report'}
        </button>
      ) : null}
      {error === null ? null : <p className="error">{error}</p>}
      {result === null ? null : (
        <div className="stack">
          <p>{result.report.summary}</p>
          {result.report.highlights.length === 0 ? null : (
            <>
              <h3>Highlights</h3>
              <ul>
                {result.report.highlights.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </>
          )}
          {result.report.watchouts.length === 0 ? null : (
            <>
              <h3>Watch-outs</h3>
              <ul>
                {result.report.watchouts.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </>
          )}
          <p className="muted">{result.report.disclaimer}</p>
          <p className="muted">
            Model {result.model} · generated {new Date(result.generatedAt).toLocaleString()}
          </p>
        </div>
      )}
    </section>
  );
}
